### ISSUE TITLE
Proposing changes towards the publishing workflow on the road to 1.1.6

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#124]
Some suggestions:

- Only the pdf  and releases files need signing and checksum
- All the other files can stay as is and not be in the export folder at all
- Instead, use GitHub features, let's make a 1.1.6 release with the related 1.1.6 tag which will generate 2 files:
    -  thgtoa_1.1.6.tar.gz 
    -  thgtoa_1.1.6.zip 
  And just sign/checksum those instead of signing each separate file, just sign the whole repo release?
- Reinstate the virustotal check for the PDF files and add the results to a separate file for guide.md/pdf and the releases. Why? Because of such things: https://threatresearch.ext.hp.com/stealthy-opendocument-malware-targets-latin-american-hotels/
- Update changelog as "unreleased" when committing. To avoid having to go back through all the changes since 1.1.6pre1 when going to 1.1.6.

**Comment by dan-kir** [comment]
I agree with the following:

- Only the guide, in the export dir needs signing and checksums.
- Tagged releases are not a bad idea. Could instead maybe include the release number in the exported filenames?
- Scanning with gitleaks, trufflehog etc is also a good idea. 

I do not think the virus total checks are required. Not sure what this accomplishes. The results could just be forged/spoofed?

After the issues we had building recently, (due to the backslashes that snuck in), I thought it might be worthwhile having a 'pre-production' branch where the build can be tested/confirmed before then merging into master. All PRs should target Anon-Planet/thgtoa:pre-prod for example. This would prevent running into the same problem again.

**Comment by pterocles** [comment]
We do not talk about #119.

I have a separate build that does exactly what you're talking about.

@dan-kir [trufflehog](https://github.com/trufflesecurity/trufflehog#trufflehog-oss-github-action) is a github action that we can add to the current configs easily. Gitleaks is [available as a pre-commit](https://github.com/zricethezav/gitleaks#pre-commit) you can add to your local repo. Github does a decent job scanning for leaks as it stands.

**Comment by dan-kir** [comment]
> After the issues we had building recently, (due to the backslashes that snuck in), I thought it might be worthwhile having a 'pre-production' branch where the build can be tested/confirmed before then merging into master. All PRs should target Anon-Planet/thgtoa:pre-prod for example. This would prevent running into the same problem again.

Can we just track releases/versions in branches? Eg. Anon-Planet/thgtoa:wip-version1-1-6

Then when ready and tested, merge to master and call it a day?
