### ISSUE TITLE
Adapt anonymousplanet.org for several projects?

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#190]
Proposal:

- Adapt layout file so that the landing page has a different title (Welcome to Anonymous Planet).
- Adapt README to list projects others than THGTOA from our organization.
- Adapt any other file in consequence 

Basically, making the landing page the ORG landing page rather than the THGTOA landing page.

Possibly, move THGTOA in the future to https://thgtoa.anonymousplanet-ng.org rather than the root domain. Like other projects will be. For consistency.

Opinions welcome. No PR proposed yet.

**Comment by pterocles** [comment]
> Adapt any other file in consequence

Can you explain?

**Comment by pterocles** [comment]
Can you mark this as a draft: "[draft] Adapt ..."

**Comment by pterocles** [comment]
Just make it immediately clear it's not important right now in the title. We're trying to avoid unnecessary PRs and Issues if they're going to be worked on at later dates and aren't something to focus on now.

**Comment by pterocles** [comment]
Let's revisit this with the new landing page.

**Comment by pterocles** [comment]
Closing, as this is more of an internal matter than to be discussed in the section.

Since this was made, we have introduced the new [landing page](https://psa.anonymousplanet.org/). The landing shows our GitHub and the Hitchhiker's Guide to Online Anonymity. It also explains more of our Matrix/Synapse instance; who are the mods, who are the admins, contact links, etc. 

Please take a moment to review the landing page if you're not familiar with our organization. We welcome all newcomers.
