### ISSUE TITLE
[Urgent] Major update of VirtualBox tutorials required with VB 7.x release

### ISSUE THREAD

**Issue by RickDeckhard** [Anon-Planet/thgtoa#265]
**Please describe the scope.**

Everything related to VirtualBox and using VirtualBox

**Please describe the solution.**

**Update tutorials accordingly to fit VirtualBox which now can emulate TPM 1.2, TPM 2.0, IOMMU, SecureBoot.**

- The <insert host OS> on VB part all need updating to reflect the changes
- HiddenVM requires update
- Possibly Whonix requires update

**Please describe alternatives.**

**None, just update**

**Give any additional relevant context.**

See VirtualBox 7.x capabilities at https://www.virtualbox.org/wiki/Changelog

**Comment by sharp-tailed** [comment]
I see that these are now supported by Vbox. But does macOS (M1/M2) now support Whonix via paravirtualization? I.e., does this work: 

- **Vbox** > **macOS (e.g., Big Sur)** > **Whonix guest boxes**

I can't test the native virtualization of macOS since I neither care for nor own a testing device. But all versions of Vbox now include support for a TPM (including a physical TPM module) and Secure Boot. The TPM can be added with the header on the motherboard on the Host OS. You can therefore run Windows 11, which requires a TPM for attestation.
