### ISSUE TITLE
Please keep this project maintained ... it's the only one of its kind. I learned so much.

### ISSUE THREAD

**Issue by yourfeetontheairandyourheadontheground** [Anon-Planet/thgtoa#33]
Don't abandon it please please

**Comment by NobodySpecial256** [comment]
I feel the need to address this concern, as it's been expressed multiple times by many people. Due to current circumstances in my life, it's difficult for me to put as much time into this project as I'd like to. However, I have no intention of abandoning this project, and promise to continue its development.

If anyone would like to help development, the best thing you can do to help is to submit PRs, ideally with tested and ready-to-merge changes, to reduce the time required for me to review and merge them.
