### ISSUE TITLE
Remove PrivacyTools

### ISSUE THREAD

**Issue by NobodySpecial256** [Anon-Planet/thgtoa#62]
As decided in #61, we'll be removing PrivacyTools from the guide due to FUD and affiliate bullshit

**Comment by thanharrison** [comment]
Likely, PTIO will see this as an affront to their validity. I think that my opinion is shared in terms of the needlessness for affiliate marketing in a guide for privacy and anonymity. It does not exist and should not exist. I understand that some profit should be made from maintaining such a website, due to upkeep and server cost, but you should not do it the way it is implemented there. It should be through donations and not motivated by greed.

**Comment by NobodySpecial256** [comment]
Let them take it as an affront to their validity. After all, it *is* exactly that. If they want to be a recommended resource they should focus more on the content of their privacy advice instead of the content of their wallets.
