### ISSUE TITLE
Secuchart addition

### ISSUE THREAD

**Issue by pterocles** [Anon-Planet/thgtoa#63]
Needs to be said that Secuchart https://bkil.gitlab.io/secuchart/ is a fantastic resource when deciding between chat/IM clients. It involves a lot of things such as the safety of the protocol (audits), E2EE status, PFS status, and whether or not there are F-droid APKs and where to see the source, etc. I've recommended this resource to many already with great feedback. I would like to place it in the list of additional resources before the comparison in the guide, so people can see a updated and maintained chart for help choosing an app to communicate safely with.

All credit to bkil on Matrix.

**Comment by thanharrison** [comment]
> We should ask the owner if we can pull data from his chart to update ours (after fact checking)

I don't see why they would have an issue of us updating our information with theirs, because it's public information.

> First I propose that we move those links (mentioned above) below our chart instead of above.

It wouldn't matter if they were above or below, the information is the same.

I'll try to get bkil onto a chat soon and ask what they think. Lately, it's harder to communicate with people when you mention our ORG but I will try.

**Comment by thanharrison** [comment]
No new changes until main is updated to the 1.1.5 tag, that's when new changes can be made and conflicts resolved. It shouldn't be much longer of a wait.
