### ISSUE TITLE
Remove OS Security from PSA  (#os-security:artemislena.eu)

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#90]
Sadly, they decided to leave the community. They should be removed from the PSA space and placed in the other rooms sections.

Our logo needs to be updated. See attachment. All their rights should also be removed if they have any. If they're admin on a section or some space. They should unadmin their privileges. If lower we should remove all their privileges.

Also see #91 

![psa2](https://user-images.githubusercontent.com/105207317/177341054-63308f43-a336-4264-9f12-b50b37f765a6.jpg)
.

**Comment by thanharrison** [comment]
This needs to be split into multiple issues:

1. Removal of mod status for someone doesn't need an issue because it's not project-related, it's Matrix-related.
2. I think the logo needs a revamp too, but I think it deserves a really good design. I myself have a few designs in mind, but I think we should hire a pro to really give it some value. Open a discussion so we can have a good amount of suggestions and feedback from the community during the process.
